'use client'

import Nav from '@/components/Navigation';
import FinanceContextProvider from '@/lib/store/context';
import AuthContextProvider from '@/lib/store/authContext';
import "./globals.css";


// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthContextProvider>
                    <FinanceContextProvider>
                        <Nav />
                        {children}
                    </FinanceContextProvider>
                </AuthContextProvider>
            </body>
        </html>
    );
}
