'use client'

import Nav from '@/components/Navigation';
import FinanceContextProvider from '@/lib/store/context';
import "./globals.css";

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <FinanceContextProvider>
                    <Nav />
                    {children}
                </FinanceContextProvider>
            </body>
        </html>
    );
}
